### ISSUE TITLE
Module not found, wetty won't start.

### ISSUE THREAD

**Issue by rodcastler** [butlerx/wetty#604]
**Describe the bug**
Wetty fails to boot after updating to 3.0.0.

**To Reproduce**
1. Update to version 3.0.0
2. Wetty stops working.

**Expected behavior**
Wetty up and running. 
When running it immediately establishes a connection with the user root (without prompting for the user), and only requests for the password. After that, you're in as root.

**Additional context**
Same issue, two different servers on the same architecture:
Failed on 5/26/2026 after being automatically updated by watchtower
Debian, Docker on OpenMediavault

**Compose file follows.**
(This exact configuration had been working flawlessly up until May/25/2026)

_services:
  wetty:
    image: wettyoss/wetty
    container_name: wetty
    ports:
      - "7681:3000"
    environment:
      - REMOTE_SSH_SERVER=192.168.YY.XX
      - REMOTE_SSH_PORT=22
      - REMOTE_SSH_USER=root
    # This forces the container to initiate the SSH connection immediately
    command: wetty --ssh-host 192.168.YY.XX --ssh-port 22 --ssh-user root
    restart: unless-stopped_

**Docker Logs Follow:**

_wetty  | Node.js v22.22.3
wetty  | node:internal/modules/cjs/loader:1433
wetty  |   throw err;
wetty  |   ^
wetty  | 
wetty  | Error: Cannot find module '/usr/src/app/wetty'
wetty  |     at Function._resolveFilename (node:internal/modules/cjs/loader:1430:15)
wetty  |     at defaultResolveImpl (node:internal/modules/cjs/loader:1040:19)
wetty  |     at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1045:22)
wetty  |     at Function._load (node:internal/modules/cjs/loader:1216:25)
wetty  |     at wrapModuleLoad (node:internal/modules/cjs/loader:254:19)
wetty  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
wetty  |     at node:internal/main/run_main_module:36:49 {
wetty  |   code: 'MODULE_NOT_FOUND',
wetty  |   requireStack: []
wetty  | }
wetty  | 
wetty  | Node.js v22.22.3_

**Comment by rodcastler** [comment]
fixed in latest release
