### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by jaypadath** [butlerx/wetty#40]
Hi, I have cloned the source and installed yarn. But yarn related commands are not working for me:
japadath@japadath:~/butlerx/wetty$ yarn
ERROR: There are no scenarios; must have at least one.
japadath@japadath:~/butlerx/wetty$ sudo yarn
[sudo] password for japadath: 
ERROR: There are no scenarios; must have at least one.
japadath@japadath:~/butlerx/wetty$ yarn -g add wetty.js
Usage: yarn [options]

yarn: error: no such option: -g

Also "npm i -g wetty.js" worked for me.  But I am getting below error while starting:
japadath@japadath:~/butlerx/wetty$ node index.js 
module.js:540
    throw err;
    ^

Error: Cannot find module '@std/esm'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/japadath/butlerx/wetty/index.js:2:11)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

Could you please help me on this ?

**Comment by mirtouf** [comment]
Hi,

which version of yarn are you using ?

**Comment by jaypadath** [comment]
yarn --version
0.22

**Comment by butlerx** [comment]
that yarn is quite out of date. try upgrading to one higher than 1.0.0.
you also don't need to do `yarn -g add wetty.js` or `npm install -g wetty.js` if you are installing from GitHub, you just need to run 
```sh 
yarn 
yarn build
```
or 
```sh 
npm install
npm build
```
while in the repo directory

**Comment by jaypadath** [comment]
Okay thanks. I have upgraded yarn version to 1.5.1 and now ssh is working with my local host on Ubuntu 16.04 system.

Is it possible to use Wetty directly in to one of my project ? Front end is angular js and node js packaging is used to connect to remote host. My requirement is to create a new page with a terminal embedded in it and I should be able to ssh to host with specific port.

From browser, while typing "http://localhost:3000", I am able to reach to ssh port. So is it possible to embed in a web page rather than invoking separately.

Thanks in advance, Jay.

**Comment by butlerx** [comment]
it should be possible though ive not done it. if you put the following in a div 
```html
<div id="overlay">
  <div class="error">
    <div id="msg"></div>
    <input type="button" onclick="location.reload();" value="reconnect" />
  </div>
</div>
<div id="terminal"></div>
<script src="node_modules/wetty.js/dist/main.js"></script>
<link rel="stylesheet" href="node_modules/wetty.js/dist/main.css" />
```
wetty wasnt designed for that so the css might need to overridden in parts but the javascript should work

**Comment by jaypadath** [comment]
Okay thanks. The problem is like I am not able to figure out how to integrate wetty into my project. In a particular folder I have installed wetty. I already have a separate npm server running. While installing some packages like "@std/esm" my current package is getting corrupted. 

Also just by adding the div as overlay did not work for me.

**Comment by nosemeocurrenada** [comment]
I'm using wetty integrated in a web.

In the html I have
`<iframe height='100%' width='100%' id='contentFrame' src=''>Iframe not supported</iframe>`

then in the js i have a function that receives the connection url from the server and change it like this
` $("#contentFrame")[0].src = connectionUri;`

and it works just fine.

In the backend I just give wetty the connection data and it opens the service on the given port
```
const wetty = require("wetty.js")
wetty(port, sshuser, sshhost, sshport, sshauth)
```
